import type { Metadata, Viewport } from "next";
import "./globals.css";
import WhatsAppChat from "@/components/WhatsApp/WhatsAppChat";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        {children}
        <WhatsAppChat />
      </body>
    </html>
  );
}
